---
title: "eds212_day2_comp2"
---

## Day 2 Computer Session 2

## Derivatives pt. 2

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Plotting functions in ggplot2

```{r}
fx = function(x) {3 * x ^ 2 + 4}

#c is concatenate, vector of 2 values
#aes ( x = x ) mapping values of x to the values stored in this c frame
# "fun" is where you put what function you're graphing
# ggplot(data = df,...)
#c just puts the 2 values (1, 100) into a vector bc fun is just looking for endpoints ( 1 and 100) 
# you can also do seq() but this version is shorter because you only need endpoints

ggplot(data.frame(x = c(1, 100)), aes(x = x)) + 
  stat_function(fun = fx)



```

## Partial Derivative

```{r}
fxyz = expression(2 * x * y + 3 * (x ^ 2) * (z ^ 3))

dfdy = D(fxyz, 'y')

#dfdy
```

## Penguins plot

```{r}
# view(penguins) in console!

# anything set to a constant should be outside of aes, anything set to a variable (i.e., island, species), should be within aes


ggplot() +
  geom_point(data = penguins, 
             aes(x = flipper_length_mm, 
                 y = body_mass_g,
                 color = species)) +
  labs(x = "Flipper length (mm)", 
       y = "Body mass (g)",
       title = "Palmer penguin body dimensions",
       subtitle = "Palmer Archipelago, Antarctica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleages at Palmer Station LTER") + 
  facet_wrap(~island) + 
  theme_minimal()

```
